services:
  globals_documents:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile
    environment:
#      HASURA_SERVICE_TOKEN_SECRET: $GLOBALS_DOCUMENTS_HASURA_SERVICE_TOKEN_SECRET_1
#      OTEL_EXPORTER_OTLP_ENDPOINT: $GLOBALS_DOCUMENTS_OTEL_EXPORTER_OTLP_ENDPOINT_1
#      OTEL_SERVICE_NAME: $GLOBALS_DOCUMENTS_OTEL_SERVICE_NAME_1
      DOCUMENTS_URI: $DOCUMENTS_URI
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
#      - 7426:8080
